language: php

php:
  - 5.4
  - 5.5

before_install:
 - composer install
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
 - wget https://scrutinizer-ci.com/ocular.phar

script:
 - phpunit --coverage-text --coverage-clover=coverage.clover
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

after_script:
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
