name: PHP Class Diagram

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pcd:
      runs-on: ubuntu-latest
      name: PHP Class Diagram
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Create output directory
          run: mkdir -p images

        - name: Create class diagram
          id: create-class-diagram
          uses: smeghead/php-class-diagram-gh-action@v0
          with:
            target-path: src
            output-path: ./images/php-class-diagram.svg
            target-repo: ${{ github.repository }}
            target-branch: ${{ github.ref_name }}

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Class_Diagram
            path: ./images/php-class-diagram.svg
            retention-days: 5

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./images
            destination_dir: ./images
